default: &default
 adapter: postgresql
 pool: 5
 timeout: 5000
 encoding: unicode
 username: efood
 password: efood
 host: localhost

development:
 <<: *default
 database: efood_dev

production:
 <<: *default
 database: efood_pro

test:
 <<: *default
 database: efood_test